### ISSUE TITLE
No controller connection with WLED firmware greater than 0.14.1

### ISSUE THREAD

**Issue by smhex** [smhex/homebridge-wled-ws#46]
**Describe The Bug:**
The plugin is not able to connect to a Wled controller running a firmware version greater than 0.14.1. 

**To Reproduce:**
Update your Wled controller to a firmware greater than 0.14.1 and restart the plugin. The last log message will be the Connect request. It will timeout.

**Expected behavior:**
Connection should be successful 

**Logs:**

```
Coming soon
```

**Environment:**

* **Plugin Version**:: 0.0.11+
* **Homebridge Version**: 1.7.0
* **Node.js Version**: 18.19.0

**Comment by mariusstrom** [comment]
Mine was able to connect to both 14.2 and 15.1b1, but it would cause the WLED device to crash and reboot. See https://github.com/Aircoookie/WLED/issues/3847 for potentially related issue on the WLED device side.

**Comment by mariusstrom** [comment]
Disabling the plugin in homebridge has caused my WLED device to be stable.

**Comment by smhex** [comment]
Thanks for your comment! I am still trying to get the crash dumps to find out what happens. My feeling is that this behavior was introduced with any version coming after 0.14.1. The Wled changelog shows updates in json buffer handling and a newer version of the AsyncWebserver was integrated. Both are involved when controlling Wled via websockets using my plugin. I stripped down my implementation to native socket handling and it immediately crashes. In the meantime the only solution is to stick on 0.14.1 if possible...

**Comment by mariusstrom** [comment]
Sadly my WLED is in an inconvenient spot to access so I can't get the crashdumps.

**Comment by smhex** [comment]
Filed an issue here: https://github.com/Aircoookie/WLED/issues/3855

**Comment by smhex** [comment]
@mariusstrom : I was able to build a WLED firmware from scratch. I monitored the serial debug output to save the crash dumps. It turned out, that there was a memory issues with the AsyncWebserver library WLED is using. A fix is underway. As soon as it is merged I will re-test. Hopefully, everything will work again.

**Comment by smhex** [comment]
Fixed in WLED 0.14.3 (https://github.com/Aircoookie/WLED/releases/tag/v0.14.3)
